name: invalid-configuration
description: A manifest to test validation functions
tags:
initialize:
  plugins:
    branch-on:
      path: 'if-branch-plugin'
      method: Branch
tree:
  children:
    child-1:
      pipeline:
        - branch-on
      config:
        branch-on:
          'region' # SB {str : any[]}
      defaults:
      inputs:
        - timestamp: '2023-12-12T00:00:00.000Z'
          region: uk-west
          duration: 1
          cpu/utilization: 10
        - timestamp: '2023-12-12T00:00:01.000Z'
          duration: 5
          cpu/utilization: 20
          region: uk-west
        - timestamp: '2023-12-12T00:00:06.000Z'
          duration: 7
          cpu/utilization: 15
          region: uk-west
        - timestamp: '2023-12-12T00:00:13.000Z'
          duration: 30
          region: uk-west
          cpu/utilization: 15
