name: branch-demo
description:
tags:
initialize:
  plugins:
    'mock-observations':
      kind: plugin
      method: MockObservations
      path: '@grnsft/if-plugins'
      global-config:
        timestamp-from: 2023-07-06T00:00
        timestamp-to: 2023-07-06T00:30
        duration: 600
        components:
          - instance-type: A1
          - instance-type: B1
        generators:
          common:
            region: uk-west
            common-key: common-val
          randint:
            cpu/utilization:
              min: 1
              max: 99
            memory/utilization:
              min: 1
              max: 99
    'branch-on':
      path: 'if-branch-plugin'
      method: Branch
tree:
  children:
    child-1:
      pipeline:
        - mock-observations
        - branch-on
      config:
        branch-on:
          region:
            - uk-north
      defaults:
        cpu/thermal-design-power: 100
        grid/carbon-intensity: 800
        device/emissions-embodied: 1533.120 # gCO2eq
        time-reserved: 3600 # 1hr in seconds
        device/expected-lifespan: 94608000 # 3 years in seconds
        resources-reserved: 1
        resources-total: 8
        functional-unit-time: '1 min'
      inputs:
