name: sample
description:
tags:
initialize:
  plugins:
    'if-branch-plugin':
      path: 'if-branch-plugin'
      method: Branch
      global-config:
        branch-on:
          region:
            - uk-north
tree:
  children:
    child-1:
      pipeline:
        - if-branch-plugin
      config:
      defaults:
      inputs:
        - timestamp: '2023-12-12T00:00:00.000Z'
          region: uk-west
          duration: 1
          cpu/utilization: 10
        - timestamp: '2023-12-12T00:00:01.000Z'
          duration: 5
          cpu/utilization: 20
          region: uk-west
        - timestamp: '2023-12-12T00:00:06.000Z'
          duration: 7
          cpu/utilization: 15
          region: uk-west
        - timestamp: '2023-12-12T00:00:13.000Z'
          duration: 30
          region: uk-west
          cpu/utilization: 15
