name: Simple
description: Simplest possible manifest to test branching.
tags:
initialize:
  plugins:
    branch-on:
      path: 'if-branch-plugin'
      method: Branch
tree:
  children:
    child-1:
      pipeline:
        - branch-on
      config:
        branch-on:
          region:
            - uk-north
      defaults:
      inputs:
        - timestamp: '2023-12-12T00:00:00.000Z'
          region: uk-west
          duration: 1